package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"text/template"

	"github.com/donatj/ghemoji"
)

var (
	pkg = flag.String("package", "ghemoji", "package name to output")
	arg = ""
)

func init() {
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage of %s [options] <file>:\n", os.Args[0])
		flag.PrintDefaults()
	}

	flag.Parse()

	if flag.NArg() != 1 {
		flag.Usage()
		os.Exit(2)
	}

	arg = flag.Arg(0)
}

const templ = `// Code generated by "ghupdate"; DO NOT EDIT

package {{.Package}}

var EmojiDataset = {{.EmojiData | printf "%#v"}}

var EmojiAliasMap = map[string]EmojiData{
	{{range $key, $val := .EmojiData}}{{if $val.Emoji}}{{range .Aliases}}	"{{.}}": EmojiDataset[{{$key}}],
	{{end}}{{end}}{{end}}}

`

type templateData struct {
	Package   string
	EmojiData ghemoji.EmojiResponse
}

func main() {
	emoji := ghemoji.EmojiResponse{}

	res, err := http.Get("https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json")
	if err != nil {
		log.Fatal(err.Error())
	}

	x := json.NewDecoder(res.Body)

	err = x.Decode(&emoji)
	if err != nil {
		log.Fatal(err.Error())
	}

	td := templateData{
		Package:   *pkg,
		EmojiData: emoji,
	}

	tmpl := template.New("code template")
	tmpl, err = tmpl.Parse(templ)
	if err != nil {
		log.Fatal(err.Error())
	}

	f, err := os.Create(arg)
	if err != nil {
		log.Fatal(err.Error())
	}

	defer f.Close()

	buffer := &bytes.Buffer{}

	err = tmpl.Execute(buffer, td)
	if err != nil {
		log.Fatal(err.Error())
	}

	out := buffer.String()
	out = strings.ReplaceAll(out, "ghemoji.EmojiData", "\nghemoji.EmojiData")
	out = strings.ReplaceAll(out, "ghemoji.Emoji", "Emoji")

	f.WriteString(out)

	log.Println("success")
}
